ALTER TABLE score_distribution DISABLE ROW LEVEL SECURITY;
ALTER TABLE admission_scores DISABLE ROW LEVEL SECURITY;
ALTER TABLE major_scores DISABLE ROW LEVEL SECURITY;
ALTER TABLE subject_requirements DISABLE ROW LEVEL SECURITY;