import dotenv from 'dotenv';
dotenv.config();

import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY;

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

const MAJOR_SCORES_DATA = [
  {
    school_name: '清华大学',
    school_code: '303',
    province: '北京',
    level: '985',
    major_name: '计算机科学与技术',
    major_group: '(03)',
    subject_requirement: '物理必选',
    year: 2025,
    min_score: 851,
    min_rank: 100,
    avg_score: 858,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '清华大学',
    school_code: '304',
    province: '北京',
    level: '985',
    major_name: '软件工程',
    major_group: '(04)',
    subject_requirement: '物理必选',
    year: 2025,
    min_score: 841,
    min_rank: 180,
    avg_score: 846,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '清华大学',
    school_code: '303',
    province: '北京',
    level: '985',
    major_name: '计算机科学与技术',
    major_group: '(03)',
    subject_requirement: '物理必选',
    year: 2023,
    min_score: 893,
    min_rank: 80,
    avg_score: 898,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '北京大学',
    school_code: '103',
    province: '北京',
    level: '985',
    major_name: '数学与应用数学',
    major_group: '(03)',
    subject_requirement: '物理必选',
    year: 2025,
    min_score: 838,
    min_rank: 220,
    avg_score: 842,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '北京大学',
    school_code: '102',
    province: '北京',
    level: '985',
    major_name: '经济学',
    major_group: '(02)',
    subject_requirement: '不限',
    year: 2025,
    min_score: 827,
    min_rank: 300,
    avg_score: 832,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '北京大学',
    school_code: '102',
    province: '北京',
    level: '985',
    major_name: '经济学',
    major_group: '(02)',
    subject_requirement: '不限',
    year: 2023,
    min_score: 841,
    min_rank: 150,
    avg_score: 845,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '复旦大学',
    school_code: '70205',
    province: '上海',
    level: '985',
    major_name: '临床医学',
    major_group: '(05)',
    subject_requirement: '物理必选',
    year: 2025,
    min_score: 821,
    min_rank: 380,
    avg_score: 826,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '复旦大学',
    school_code: '70204',
    province: '上海',
    level: '985',
    major_name: '金融学',
    major_group: '(04)',
    subject_requirement: '不限',
    year: 2025,
    min_score: 819,
    min_rank: 400,
    avg_score: 824,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '上海交通大学',
    school_code: '70402',
    province: '上海',
    level: '985',
    major_name: '电子信息工程',
    major_group: '(02)',
    subject_requirement: '物理必选',
    year: 2025,
    min_score: 826,
    min_rank: 340,
    avg_score: 830,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '上海交通大学医学院',
    school_code: '77302',
    province: '上海',
    level: '985',
    major_name: '临床医学（八年制）',
    major_group: '(02)',
    subject_requirement: '物理必选',
    year: 2025,
    min_score: 805,
    min_rank: 550,
    avg_score: 810,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '浙江大学',
    school_code: '95003',
    province: '浙江',
    level: '211',
    major_name: '计算机科学与技术',
    major_group: '(03)',
    subject_requirement: '物理必选',
    year: 2025,
    min_score: 816,
    min_rank: 440,
    avg_score: 820,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '浙江大学',
    school_code: '95002',
    province: '浙江',
    level: '211',
    major_name: '电气工程及其自动化',
    major_group: '(02)',
    subject_requirement: '物理必选',
    year: 2025,
    min_score: 806,
    min_rank: 520,
    avg_score: 810,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '中国人民大学',
    school_code: '202',
    province: '北京',
    level: '985',
    major_name: '法学',
    major_group: '(02)',
    subject_requirement: '不限',
    year: 2025,
    min_score: 804,
    min_rank: 540,
    avg_score: 808,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '中国人民大学',
    school_code: '202',
    province: '北京',
    level: '985',
    major_name: '法学',
    major_group: '(02)',
    subject_requirement: '不限',
    year: 2023,
    min_score: 800,
    min_rank: 580,
    avg_score: 804,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '南京大学',
    school_code: '77501',
    province: '江苏',
    level: '985',
    major_name: '物理学',
    major_group: '(01)',
    subject_requirement: '物理必选',
    year: 2025,
    min_score: 789,
    min_rank: 680,
    avg_score: 793,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '武汉大学',
    school_code: '202602',
    province: '湖北',
    level: '985',
    major_name: '测绘工程',
    major_group: '(02)',
    subject_requirement: '物理必选',
    year: 2025,
    min_score: 763,
    min_rank: 920,
    avg_score: 768,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '西安交通大学',
    school_code: '268103',
    province: '陕西',
    level: '985',
    major_name: '机械工程',
    major_group: '(03)',
    subject_requirement: '物理必选',
    year: 2025,
    min_score: 780,
    min_rank: 760,
    avg_score: 784,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '华中科技大学',
    school_code: '173702',
    province: '湖北',
    level: '985',
    major_name: '光电信息科学与工程',
    major_group: '(02)',
    subject_requirement: '物理必选',
    year: 2025,
    min_score: 751,
    min_rank: 1080,
    avg_score: 756,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '北京航空航天大学',
    school_code: '602',
    province: '北京',
    level: '985',
    major_name: '航空航天工程',
    major_group: '(02)',
    subject_requirement: '物理必选',
    year: 2025,
    min_score: 789,
    min_rank: 740,
    avg_score: 793,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '北京航空航天大学',
    school_code: '602',
    province: '北京',
    level: '985',
    major_name: '航空航天工程',
    major_group: '(02)',
    subject_requirement: '物理必选',
    year: 2024,
    min_score: 781,
    min_rank: 800,
    avg_score: 785,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '北京航空航天大学',
    school_code: '602',
    province: '北京',
    level: '985',
    major_name: '航空航天工程',
    major_group: '(02)',
    subject_requirement: '物理必选',
    year: 2023,
    min_score: 742,
    min_rank: 1200,
    avg_score: 748,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '北京邮电大学',
    school_code: '1380',
    province: '北京',
    level: '211',
    major_name: '通信工程',
    major_group: '(80)',
    subject_requirement: '物理必选',
    year: 2025,
    min_score: 759,
    min_rank: 1000,
    avg_score: 764,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '北京邮电大学',
    school_code: '1380',
    province: '北京',
    level: '211',
    major_name: '通信工程',
    major_group: '(80)',
    subject_requirement: '物理必选',
    year: 2024,
    min_score: 757,
    min_rank: 1020,
    avg_score: 762,
    batch: '本科提前批',
    source: '海南省考试局',
  },
  {
    school_name: '北京邮电大学',
    school_code: '1380',
    province: '北京',
    level: '211',
    major_name: '通信工程',
    major_group: '(80)',
    subject_requirement: '物理必选',
    year: 2023,
    min_score: 751,
    min_rank: 1080,
    avg_score: 756,
    batch: '本科提前批',
    source: '海南省考试局',
  },
];

async function saveToSupabase() {
  console.log('开始导入专业分数线数据...');
  
  try {
    const batchSize = 50;
    for (let i = 0; i < MAJOR_SCORES_DATA.length; i += batchSize) {
      const batch = MAJOR_SCORES_DATA.slice(i, i + batchSize);
      const { error } = await supabase.from('major_scores').insert(batch);
      
      if (error) {
        console.error('插入失败:', error.message);
        return;
      }
      
      console.log(`  成功插入 ${batch.length} 条记录`);
    }
    
    console.log(`\n共插入 ${MAJOR_SCORES_DATA.length} 条记录`);
    console.log('导入完成！');
    
  } catch (error) {
    console.error('保存失败:', error.message);
  }
}

saveToSupabase().catch(console.error);